version: "3.8"

services:
  docker:
    platform: linux/amd64
    image: docker:dind
    privileged: true
    ports:
      - "3376:2376"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - jenkins
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home

  jenkins:
    platform: linux/amd64
    image: mrabbah/jenkins:2.346.3-jdk11-dind
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:3376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    
networks:
  jenkins: { }

volumes:
  jenkins-docker-certs: { }
  jenkins-data: { }